apiVersion: v1
kind: Service
metadata:
  name: my-app-service-nodeport
spec:
  type: NodePort
  selector:
    app: my-app-deployment
  ports:
  - name: http
    port: 3000
    targetPort: 3001
    nodePort: 30000